services:
  api-nest:
    restart: always
    build:
      context: ./backend/api-nest
    container_name: mi-nestjs-container
    environment:
      DATABASE_URL: postgres://postgres:postgres@54.208.77.229:5432/usuario
    ports:
      - "3000:3000"
    networks:
      - mi_red

  api-go:
    restart: always
    build:
      context: ./backend/api-fiber
    container_name: mi-go-container
    environment:
      DB_HOST: 54.208.77.229
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mi_password
      DB_NAME: cursos
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: root:mi_password@tcp(54.208.77.229:3306)/cursos?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci
      GOOSE_MIGRATION_DIR: ./database/migrations
      GOOSE_TABLE: custom.goose_migrations
    ports:
      - "8070:8070"
    networks:
      - mi_red

  api-fastapi:
    restart: always
    build:
      context: ./backend/api-fast
    container_name: mi-fastapi-container
    environment:
      MONGO_URL: mongodb://54.208.77.229:27017
    ports:
      - "8080:80"
    networks:
      - mi_red
    volumes:
      - ./docs:/app/docs

  orquestador:
    restart: always
    build:
      context: ./backend/api-orquestador
    container_name: orquestador
    environment:
      USUARIOS_SERVICE_URL: http://api-nest:3000
      CURSOS_SERVICE_URL: http://api-go:8070
      NOTAS_SERVICE_URL: http://api-fastapi:80
    ports:
      - "9000:9000"
    depends_on:
      - api-nest
      - api-go
      - api-fastapi
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge
