services:
  postgres-db:
    restart: always
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuario
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mi_red

  mysql-db:
    restart: always
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mi_password
      MYSQL_DATABASE: cursos
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mi_red

  mongo-db:
    restart: always
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mi_red

  data-seeder:
    restart: always
    build: .
    container_name: data-seeder
    env_file:
      - .env
    depends_on:
      - postgres-db
      - mysql-db
      - mongo-db
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge

volumes:
  pgdata:
  mysqldata:
  mongodata:
